### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by timohausmann** [pencil-js/spritesheet#3]
Hey, I just tried the usage example and I got a few errors on node v14.15.0:

- `Must use import to load ES Module`
- `ReferenceError: writeFileSync is not defined` 

Here is a fixed version:

```js
import spritesheet from "@pencil.js/spritesheet";
import fs from "fs";

// List of files to pack
const files = ["image1.png", "image2.jpg", "image3.gif"];
const options = {
    outputFormat: "png",
};
// Call the async function and extract the json and image values
(async () => {
    const { json, image } = await spritesheet(files, options);
    // Write the files (for example)
    fs.writeFileSync("example.png", image);
    fs.writeFileSync("example.json", JSON.stringify(json));
})();
```

Since you use `.mjs` I also had to add `"type": "module"` to my package.json.

Also, this line throws an error `Unknown file extension ".json"`for me. This may be related to mjs, where importing json is still experimental (https://nodejs.org/api/esm.html#esm_json_modules). 

https://github.com/pencil-js/spritesheet/blob/e5014f3a51c52b87d23805332ef937cbe53c7d23/index.mjs#L4

After fixing that and trying to load the spritesheet with PIXI.js I noticed the JSON is missing the `meta.image` property, which is expected by PIXI to reference the spritesheet file name.

**Comment by GMartigny** [comment]
Hi,

Thanks a lot for the review.
I'll patch everything up and a new version will come right after that.

**Comment by GMartigny** [comment]
Fixed in https://github.com/pencil-js/spritesheet/releases/tag/v1.5.0
